# PCA

In [1]:
from pandas import read_csv

In [2]:
data = read_csv('snd-dataset.csv')

data.head()

Duration   Loudness  LogAttackTime  Tempo  Tempo.confidence  \
0   24.688000  -9.428771       0.643956    122          0.150326   
1    9.743673 -15.724195      -1.538928     99          0.952932   
2    2.965000 -41.118546      -0.108449     98          0.000000   
3  212.834106 -13.990514       1.079394     94          0.661590   
4    1.985306 -12.687588      -0.707071    125          0.000000   

   TemporalCentroid        Pitch  Pitch.confidence       Key  Key.confidence  \
0          0.554729   150.475891               0.0   A minor        0.670985   
1          0.515523   172.650284               0.0  A# major        0.545118   
2          0.436209  1856.814087               0.0  C# minor        0.359346   
3          0.471911   233.854294               0.0   B major        0.878675   
4          0.517171   269.756226               0.0   C major        0.736795   

    Loop  
0  False  
1   True  
2  False  
3  False  
4  False

In [3]:
# 11 columnas de datos
data.shape

(1711, 11)

In [4]:
# Descarto columnas que no se van a usar por ahora
# Tip: axis number (0 for rows and 1 for columns)
data = data.drop("Tempo.confidence", axis=1);
data = data.drop("Pitch.confidence", axis=1);
data = data.drop("Key.confidence", axis=1);
data = data.drop("Loop", axis=1);

data.head()

Duration   Loudness  LogAttackTime  Tempo  TemporalCentroid        Pitch  \
0   24.688000  -9.428771       0.643956    122          0.554729   150.475891   
1    9.743673 -15.724195      -1.538928     99          0.515523   172.650284   
2    2.965000 -41.118546      -0.108449     98          0.436209  1856.814087   
3  212.834106 -13.990514       1.079394     94          0.471911   233.854294   
4    1.985306 -12.687588      -0.707071    125          0.517171   269.756226   

        Key  
0   A minor  
1  A# major  
2  C# minor  
3   B major  
4   C major

In [5]:
key_to_number_list = ['A minor', 'A major', 'A# minor', 'A# major', 'B minor', 'B major', 'C minor', 'C major', 'C# minor', 'C# major', 'D minor', 'D major', 'D# minor', 'D# major','E minor', 'E major', 'F minor', 'F major', 'F# minor', 'F# major', 'G minor', 'G major','G# minor', 'G# major']

def keyToNumber(x_value):
    return [i for i,x in enumerate(key_to_number_list) if x == x_value][0]

In [6]:
# test
keyToNumber('B minor')

4

In [7]:
# Mapeo de las tonalidades 'en texto' a categorias numéricas
data['Key'] = data['Key'].map(keyToNumber)

In [8]:
data.head()

Duration   Loudness  LogAttackTime  Tempo  TemporalCentroid        Pitch  \
0   24.688000  -9.428771       0.643956    122          0.554729   150.475891   
1    9.743673 -15.724195      -1.538928     99          0.515523   172.650284   
2    2.965000 -41.118546      -0.108449     98          0.436209  1856.814087   
3  212.834106 -13.990514       1.079394     94          0.471911   233.854294   
4    1.985306 -12.687588      -0.707071    125          0.517171   269.756226   

   Key  
0    0  
1    3  
2    8  
3    5  
4    7

In [9]:
X = data
#y = data["Key"]

In [10]:
from sklearn.decomposition import PCA

pca = PCA()
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [11]:
pca

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [12]:
pca.n_components_

7

In [13]:
# Nota: En sklearn PCA esta implementado como una descomposición SVD
# Libro hands on ML, p.214 (chapter 8)
pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)
pca.explained_variance_ratio_

array([0.92422762, 0.0732374 ])

# Conclusión parcial

Hasta acá esta mal porque 'Key' es una variable categórica
y no se normalizaron los datos


# Rearmado

## Escalado de los datos (normalización)
Media = 0 y varianza = 1

    http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.scale.html



In [14]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
import numpy as np

X = data.drop('Key', axis=1)
X = data
X_scaled = scale(X, axis=0, with_mean=True, with_std=True, copy=True)

In [15]:
import pandas as pd
df = pd.DataFrame(X_scaled)

df.shape

(1711, 7)

In [16]:
df.head()

0         1         2         3         4         5         6
0 -0.863956  0.980326 -0.274263  0.228131  0.775030 -0.274007 -1.569148
1 -0.958866  0.083658 -2.273533 -0.611371  0.213123 -0.233947 -1.148529
2 -1.001917 -3.533299 -0.963379 -0.647871 -0.923631  2.808588 -0.447497
3  0.330945  0.330590  0.124548 -0.793872 -0.411946 -0.123379 -0.868116
4 -1.008139  0.516167 -1.511648  0.337631  0.236739 -0.058520 -0.587703

In [17]:
# Nota: En sklearn PCA esta implementado como una descomposición SVD
# Libro hands on ML, p.214 (chapter 8)

pca = PCA()
pca.fit(X_scaled)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [18]:
# cantidad de componentes resultantes
pca.n_components_

7

In [19]:
# estos son los autovalores (ordenados de mayor a menor)
pca.explained_variance_

array([1.86825943, 1.12846829, 1.02609944, 0.9663424 , 0.80478083,
       0.75220448, 0.4579387 ])

In [20]:
avalores = pca.explained_variance_
avalores[0]/sum(avalores)

0.2667382165108527

In [21]:
# y esto muestra la 'variabilidad' que aporta cada componente
# (lo que representa en porcentaje)
pca.explained_variance_ratio_

array([0.26673822, 0.16111554, 0.14649996, 0.13796823, 0.1149015 ,
       0.10739498, 0.06538158])

In [22]:
# Y el acumulado agregando dimensiones
np.cumsum(pca.explained_variance_ratio_)

array([0.26673822, 0.42785375, 0.57435371, 0.71232195, 0.82722344,
       0.93461842, 1.        ])

# Conclusión

*Recién con 4 dimensiones tengo algo interesante*
Pero en realidad hacen falta 5



### Ecuación del modelo



In [23]:
# componente 0
pca.components_.T[:,0]

array([ 0.56514967,  0.23616014,  0.60179984,  0.14406817,  0.41395542,
       -0.24782713, -0.09559384])

In [24]:
# componente 1 (autovector del autovalor 1)
pca.components_.T[:,1]

array([ 0.07359558, -0.64160527,  0.14065051,  0.00767842,  0.39245231,
        0.61941984, -0.15932702])